# Generated by Django 6.0.6 on 2026-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(choices=[('hero', 'HERO'), ('stats', 'STATS')], default='hero', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
