# Generated by Django 6.0.6 on 2026-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberApp', '0002_sectionimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('stats', 'STATS')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='sections/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SectionImages',
        ),
    ]
